# Generated by Django 3.1.2 on 2020-10-29 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spellings', '0002_wordlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('score', models.SmallIntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spellings.wordlist')),
            ],
        ),
    ]
